version: '3.8'

services:
  # MongoDB shared by all KATO instances
  mongodb:
    image: mongo:4.4
    container_name: kato-mongodb-v2
    # Dynamic port - remove if you want MongoDB only accessible internally
    ports:
      - "27017"  # Random external port, or remove this line entirely
    volumes:
      - mongo-data-v2:/data/db
    networks:
      - kato-network-v2
    command: mongod --replSet rs0 --bind_ip_all
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB replica set initializer
  mongodb-init:
    image: mongo:4.4
    container_name: kato-mongodb-init-v2
    depends_on:
      - mongodb
    networks:
      - kato-network-v2
    command: >
      bash -c "
        for i in {1..30}; do
          if mongo --host mongodb:27017 --eval '
            rs.initiate({
              _id: \"rs0\",
              members: [{_id: 0, host: \"mongodb:27017\"}]
            })
          ' 2>/dev/null; then
            echo 'Replica set initialized successfully'
            break
          fi
          echo 'Waiting for MongoDB to be ready... (attempt $$i/30)'
          sleep 2
        done
      "
    restart: "no"

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: kato-qdrant-v2
    # Dynamic port - remove if you want Qdrant only accessible internally
    ports:
      - "6333"  # Random external port
    volumes:
      - qdrant-data-v2:/qdrant/storage
    networks:
      - kato-network-v2
    restart: unless-stopped

  # Redis for session storage (new in v2.0)
  redis:
    image: redis:7-alpine
    container_name: kato-redis-v2
    # Dynamic port - remove if you want Redis only accessible internally
    ports:
      - "6379"  # Random external port
    volumes:
      - redis-data-v2:/data
    networks:
      - kato-network-v2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # KATO v2.0 Primary Instance with Session Support
  kato-primary-v2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: kato:v2
    container_name: kato-primary-v2
    environment:
      - PROCESSOR_ID=primary-v2
      - PROCESSOR_NAME=Primary-v2
      # Internal container names for service discovery
      - MONGO_BASE_URL=mongodb://mongodb:27017/?replicaSet=rs0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379
      - MAX_PATTERN_LENGTH=0
      - PERSISTENCE=5
      - RECALL_THRESHOLD=0.1
      - LOG_LEVEL=INFO
      - SESSION_TTL=3600
      - ENABLE_V2_FEATURES=true
    ports:
      - "8000"  # Dynamic external port mapping
    networks:
      - kato-network-v2
    depends_on:
      - mongodb-init
      - qdrant
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/v2/health', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "kato.service=primary"
      - "kato.version=v2"

  # KATO v2.0 Testing Instance (for isolated testing)
  kato-testing-v2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: kato:v2
    container_name: kato-testing-v2
    environment:
      - PROCESSOR_ID=testing-v2
      - PROCESSOR_NAME=Testing-v2
      # Internal container names for service discovery
      - MONGO_BASE_URL=mongodb://mongodb:27017/?replicaSet=rs0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379
      - MAX_PATTERN_LENGTH=10
      - PERSISTENCE=5
      - RECALL_THRESHOLD=0.1
      - LOG_LEVEL=DEBUG
      - SESSION_TTL=1800
      - ENABLE_V2_FEATURES=true
    ports:
      - "8000"  # Dynamic external port mapping
    networks:
      - kato-network-v2
    depends_on:
      - mongodb-init
      - qdrant
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/v2/health', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "kato.service=testing"
      - "kato.version=v2"

  # KATO v2.0 Analytics Instance (auto-learning enabled)
  kato-analytics-v2:
    build:
      context: .
      dockerfile: Dockerfile.v2
    image: kato:v2
    container_name: kato-analytics-v2
    environment:
      - PROCESSOR_ID=analytics-v2
      - PROCESSOR_NAME=Analytics-v2
      # Internal container names for service discovery
      - MONGO_BASE_URL=mongodb://mongodb:27017/?replicaSet=rs0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379
      - MAX_PATTERN_LENGTH=50
      - PERSISTENCE=10
      - RECALL_THRESHOLD=0.5
      - LOG_LEVEL=INFO
      - SESSION_TTL=7200
      - ENABLE_V2_FEATURES=true
    ports:
      - "8000"  # Dynamic external port mapping
    networks:
      - kato-network-v2
    depends_on:
      - mongodb-init
      - qdrant
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/v2/health', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "kato.service=analytics"
      - "kato.version=v2"

networks:
  kato-network-v2:
    driver: bridge

volumes:
  mongo-data-v2:
  qdrant-data-v2:
  redis-data-v2: