# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from kato import kato_proc_pb2 as kato_dot_kato__proc__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kato/kato_proc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KatoEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetName = channel.unary_unary(
                '/kato_proc.KatoEngine/GetName',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/kato_proc.KatoEngine/Observe',
                request_serializer=kato_dot_kato__proc__pb2.Observation.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.ObservationResponse.FromString,
                _registered_method=True)
        self.Learn = channel.unary_unary(
                '/kato_proc.KatoEngine/Learn',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.StartSleeping = channel.unary_unary(
                '/kato_proc.KatoEngine/StartSleeping',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.StopSleeping = channel.unary_unary(
                '/kato_proc.KatoEngine/StopSleeping',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.StartPredicting = channel.unary_unary(
                '/kato_proc.KatoEngine/StartPredicting',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.StopPredicting = channel.unary_unary(
                '/kato_proc.KatoEngine/StopPredicting',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.UpdateGenes = channel.unary_unary(
                '/kato_proc.KatoEngine/UpdateGenes',
                request_serializer=kato_dot_kato__proc__pb2.GeneData.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.IncrementRecallThreshold = channel.unary_unary(
                '/kato_proc.KatoEngine/IncrementRecallThreshold',
                request_serializer=kato_dot_kato__proc__pb2.Increment.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetGene = channel.unary_unary(
                '/kato_proc.KatoEngine/GetGene',
                request_serializer=kato_dot_kato__proc__pb2.Gene.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.ShowStatus = channel.unary_unary(
                '/kato_proc.KatoEngine/ShowStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetTime = channel.unary_unary(
                '/kato_proc.KatoEngine/GetTime',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetPerceptData = channel.unary_unary(
                '/kato_proc.KatoEngine/GetPerceptData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/kato_proc.KatoEngine/GetModel',
                request_serializer=kato_dot_kato__proc__pb2.Name.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/kato_proc.KatoEngine/DeleteModel',
                request_serializer=kato_dot_kato__proc__pb2.Name.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.UpdateModel = channel.unary_unary(
                '/kato_proc.KatoEngine/UpdateModel',
                request_serializer=kato_dot_kato__proc__pb2.ModelUpdate.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetVector = channel.unary_unary(
                '/kato_proc.KatoEngine/GetVector',
                request_serializer=kato_dot_kato__proc__pb2.Name.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetWorkingMemory = channel.unary_unary(
                '/kato_proc.KatoEngine/GetWorkingMemory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.ClearWorkingMemory = channel.unary_unary(
                '/kato_proc.KatoEngine/ClearWorkingMemory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.ClearAllMemory = channel.unary_unary(
                '/kato_proc.KatoEngine/ClearAllMemory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetPredictions = channel.unary_unary(
                '/kato_proc.KatoEngine/GetPredictions',
                request_serializer=kato_dot_kato__proc__pb2.UniqueId.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/kato_proc.KatoEngine/Ping',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.TargetClass = channel.unary_unary(
                '/kato_proc.KatoEngine/TargetClass',
                request_serializer=kato_dot_kato__proc__pb2.TargetClassRequest.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.TargetClear = channel.unary_unary(
                '/kato_proc.KatoEngine/TargetClear',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=kato_dot_kato__proc__pb2.StandardResponse.FromString,
                _registered_method=True)


class KatoEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Learn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSleeping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSleeping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPredicting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPredicting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGenes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementRecallThreshold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPerceptData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkingMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearWorkingMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearAllMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TargetClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TargetClear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KatoEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetName,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=kato_dot_kato__proc__pb2.Observation.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.ObservationResponse.SerializeToString,
            ),
            'Learn': grpc.unary_unary_rpc_method_handler(
                    servicer.Learn,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'StartSleeping': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSleeping,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'StopSleeping': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSleeping,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'StartPredicting': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPredicting,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'StopPredicting': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPredicting,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'UpdateGenes': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGenes,
                    request_deserializer=kato_dot_kato__proc__pb2.GeneData.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'IncrementRecallThreshold': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementRecallThreshold,
                    request_deserializer=kato_dot_kato__proc__pb2.Increment.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'GetGene': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGene,
                    request_deserializer=kato_dot_kato__proc__pb2.Gene.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'ShowStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'GetPerceptData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerceptData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=kato_dot_kato__proc__pb2.Name.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=kato_dot_kato__proc__pb2.Name.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=kato_dot_kato__proc__pb2.ModelUpdate.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'GetVector': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVector,
                    request_deserializer=kato_dot_kato__proc__pb2.Name.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'GetWorkingMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkingMemory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'ClearWorkingMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearWorkingMemory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'ClearAllMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearAllMemory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'GetPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictions,
                    request_deserializer=kato_dot_kato__proc__pb2.UniqueId.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'TargetClass': grpc.unary_unary_rpc_method_handler(
                    servicer.TargetClass,
                    request_deserializer=kato_dot_kato__proc__pb2.TargetClassRequest.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
            'TargetClear': grpc.unary_unary_rpc_method_handler(
                    servicer.TargetClear,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=kato_dot_kato__proc__pb2.StandardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kato_proc.KatoEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kato_proc.KatoEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KatoEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetName',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/Observe',
            kato_dot_kato__proc__pb2.Observation.SerializeToString,
            kato_dot_kato__proc__pb2.ObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Learn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/Learn',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSleeping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/StartSleeping',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSleeping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/StopSleeping',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPredicting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/StartPredicting',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPredicting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/StopPredicting',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGenes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/UpdateGenes',
            kato_dot_kato__proc__pb2.GeneData.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementRecallThreshold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/IncrementRecallThreshold',
            kato_dot_kato__proc__pb2.Increment.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetGene',
            kato_dot_kato__proc__pb2.Gene.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/ShowStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetTime',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPerceptData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetPerceptData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetModel',
            kato_dot_kato__proc__pb2.Name.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/DeleteModel',
            kato_dot_kato__proc__pb2.Name.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/UpdateModel',
            kato_dot_kato__proc__pb2.ModelUpdate.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetVector',
            kato_dot_kato__proc__pb2.Name.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkingMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetWorkingMemory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearWorkingMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/ClearWorkingMemory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearAllMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/ClearAllMemory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/GetPredictions',
            kato_dot_kato__proc__pb2.UniqueId.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/Ping',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TargetClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/TargetClass',
            kato_dot_kato__proc__pb2.TargetClassRequest.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TargetClear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kato_proc.KatoEngine/TargetClear',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            kato_dot_kato__proc__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
